version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres-fichas
    environment:
      POSTGRES_DB: fichas_utez_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
